######################################################################
#
#  Name ............ LiDIA/src/base/interfaces/memory/default/makefile
#
#  Author       : Thomas Papanikolaou, Thomas Pfahler
#  Copyright    : 1994-1999 by the LiDIA Group
#                 Technische Universitaet Darmstadt
#
# $Id: makefile,v 1.1.1.1 2001/05/02 16:28:03 lidiaadm Exp $

all:
	@echo "use no memory manager"

#
# Clean
#

clean:
	@echo "nothing to clean"
veryclean:      clean
distclean:      veryclean

#
# End Of Makefile
#
